# -*- coding: utf-8 -*-
"""test B2W

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jRrhfJ_mbI_MIwfCoAC_S2srDR8c9FmO
"""

def area (larg, comp):
    a= larg* comp
    print(f'A área de um terreno {larg}x{comp} é de {a}m².')



print('Controle de terrenos')
print('_'* 20)
l = float(input('Largura (m): '))
c= float(input(' COMPRIMENTO (m): '))
area(l, c)